export const API_ROUTES = {
  AUTH: {
    SIGNUP: "/auth/signup",
    LOGIN: "/auth/login",
    VERIFY_OTP: "/auth/verify-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    GOOGLE: "/auth/google",
    REFRESH: "/auth/refresh",
    CHANGE_PASSWORD: "/auth/change-password",
    PROFILE: "/auth/profile",
  },
  ADMIN: {
    USERS: "/admin/users",
    USER_ACTION: (id: string, action: string) => `/admin/users/${id}/${action}`,
    USER_BY_ID: (id: string) => `/admin/users/${id}`,
    USER_STATUS: (id: string) => `/admin/users/${id}/status`,
    USER_UNBLOCK: (id: string) => `/admin/users/${id}/unblock`,
    PROVIDERS: "/admin/providers",
    PROVIDERS_PENDING: "/admin/providers/pending",
    PROVIDER_BY_ID: (id: string) => `/admin/providers/${id}`,
    PROVIDER_VERIFY: (id: string) => `/admin/providers/${id}/verification`,
    PROVIDER_STATUS: (id: string) => `/admin/providers/${id}/status`,
    SERVICES: "/admin/services",
    DELETE_SERVICE: (id: string) => `/admin/services/${id}`,
    DASHBOARD_STATS: "/admin/dashboard/stats",
    DASHBOARD_REVENUE: "/admin/dashboard/revenue",
    DASHBOARD_USER_GROWTH: "/admin/dashboard/user-growth",
    REPORTS: "/admin/reports",
    REPORT_RESOLVE: (reportId: string) => `/admin/reports/${reportId}/resolve`,
    ALL_BOOKINGS: "/admin/bookings",
    BOOKING_BY_ID: (id: string) => `/admin/bookings/${id}`,
  },
  BOOKINGS: {
    SLOTS: "/bookings/slots",
    CREATE: "/bookings",
    MY_BOOKINGS: "/bookings/my-bookings",
    PROVIDER_JOBS: "/bookings/provider/my-jobs",
    DETAIL: (id: string) => `/bookings/detail/${id}`,
    CANCEL: (id: string) => `/bookings/${id}/cancel`,
    RESCHEDULE: (id: string) => `/bookings/${id}/reschedule`,
    ACCEPT_RESCHEDULE: (id: string) => `/bookings/${id}/accept-reschedule`,
    REJECT_RESCHEDULE: (id: string) => `/bookings/${id}/reject-reschedule`,
    ACCEPT: (id: string) => `/bookings/${id}/accept`,
    STATUS: (id: string) => `/bookings/${id}/status`,
    PROVIDER_CANCEL: (id: string) => `/bookings/${id}/provider-cancel`,
    PROVIDER_RESCHEDULE: (id: string) => `/bookings/${id}/provider-reschedule`,
    ARRIVAL_OTP_GENERATE: (id: string) => `/bookings/${id}/arrival-otp/generate`,
    ARRIVAL_OTP_VERIFY: (id: string) => `/bookings/${id}/arrival-otp/verify`,
    COMPLETION_OTP_GENERATE: (id: string) => `/bookings/${id}/completion-otp/generate`,
    COMPLETION_OTP_VERIFY: (id: string) => `/bookings/${id}/completion-otp/verify`,
  },
  PROVIDER: {
    PROFILE: "/provider/profile",
    LOCATION: "/provider/location",
    SERVICE_DETAILS: "/provider/service-details",
    VERIFY_DOCS: "/provider/verify-docs",
    BANK_DETAILS: "/provider/bank-details",
    REAPPLY: "/provider/reapply",
    AVAILABILITY: "/provider/availability",
  },
  PROVIDERS: {
    LIST: "/providers",
  },
  SERVICES: {
    LIST: "/services",
  },
  REVIEWS: {
    CREATE: "/reviews",
    BY_PROVIDER: (providerId: string) => `/reviews/provider/${providerId}`,
    LIKE: (reviewId: string) => `/reviews/${reviewId}/like`,
  },
  DASHBOARD: {
    USER: "/dashboard/user",
    PROVIDER: "/dashboard/provider",
  },
  PAYMENTS: {
    CREATE_CHECKOUT: "/payments/create-checkout-session",
    VERIFY: "/payments/verify-payment",
    WALLET_PAY: "/payments/wallet-pay",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  WALLET: {
    GET: "/wallet",
  },
  CHAT: {
    CONVERSATIONS: "/chat/conversations",
    CONVERSATION_BY_ID: (id: string) => `/chat/conversations/${id}`,
    HISTORY: (id: string) => `/chat/${id}`,
    MARK_READ: (id: string) => `/chat/${id}/read`,
  },
  REPORTS: {
    CREATE: "/reports",
    MY_REPORTS: "/reports/my",
    ALL: "/reports/all",
    BY_ID: (id: string) => `/reports/${id}`,
    ACTION: (id: string) => `/reports/${id}/action`,
  },
};